class UIManager:
    def __init__(self, screen: pygame.Surface, font: pygame.font.Font): ...
    def draw_menu(self) -> None: ...
    def draw_pause(self, speed: float) -> None: ...
    def draw_hud(self, creatures: int, fps: float) -> None: ...